# ansible-orchestration-win role
---
- name: create c:\temp folder
  win_file:
    path: "{{ win_tempdir }}"
    state: directory

- name: upload concurrentusers.ps1
  win_copy:
    src: concurrentusers.ps1
    dest: "{{ win_tempdir }}"

- name: set maxconcurrent users for winrs
  win_shell: "powershell -ExecutionPolicy ByPass {{ win_tempdir }}concurrentusers.ps1"
  args:
    creates: "{{ win_tempdir }}concurrentusers.done"
    chdir: "{{ win_tempdir }}"
